// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Hanselminutes {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("HomeViewController")]
	public partial class HomeViewController {
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("DisplayButtonPressed:")]
		partial void DisplayButtonPressed (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Export("PlayButtonPressed:")]
		partial void PlayButtonPressed (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				return ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
			}
			set {
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("progressBar")]
		private MonoTouch.UIKit.UIProgressView progressBar {
			get {
				return ((MonoTouch.UIKit.UIProgressView)(this.GetNativeField("progressBar")));
			}
			set {
				this.SetNativeField("progressBar", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("tableView")]
		private MonoTouch.UIKit.UITableView tableView {
			get {
				return ((MonoTouch.UIKit.UITableView)(this.GetNativeField("tableView")));
			}
			set {
				this.SetNativeField("tableView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("modalButton")]
		private MonoTouch.UIKit.UIButton modalButton {
			get {
				return ((MonoTouch.UIKit.UIButton)(this.GetNativeField("modalButton")));
			}
			set {
				this.SetNativeField("modalButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("slider")]
		private MonoTouch.UIKit.UISlider slider {
			get {
				return ((MonoTouch.UIKit.UISlider)(this.GetNativeField("slider")));
			}
			set {
				this.SetNativeField("slider", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("totalTime")]
		private MonoTouch.UIKit.UILabel totalTime {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("totalTime")));
			}
			set {
				this.SetNativeField("totalTime", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("currentTime")]
		private MonoTouch.UIKit.UILabel currentTime {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("currentTime")));
			}
			set {
				this.SetNativeField("currentTime", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("displayButton")]
		private MonoTouch.UIKit.UIButton displayButton {
			get {
				return ((MonoTouch.UIKit.UIButton)(this.GetNativeField("displayButton")));
			}
			set {
				this.SetNativeField("displayButton", value);
			}
		}
	}
}
