// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Hanselminutes {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("PlayerViewController")]
	public partial class PlayerViewController {
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("dismissModal:")]
		partial void dismissModal (MonoTouch.UIKit.UIBarButtonItem sender);

		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				return ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
			}
			set {
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("itemRight")]
		private MonoTouch.UIKit.UIBarButtonItem itemRight {
			get {
				return ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("itemRight")));
			}
			set {
				this.SetNativeField("itemRight", value);
			}
		}
	}
}
